services:
    mongodb-primary:
        extends:
            file: "./docker/docker-compose-db.yml"
            service: mongodb-primary
    mongodb-secondary-0:
        extends:
            file: "./docker/docker-compose-db.yml"
            service: mongodb-secondary-0
    mongodb-secondary-1:
        extends:
            file: "./docker/docker-compose-db.yml"
            service: mongodb-secondary-1
    redis:
        extends:
            file: "./docker/docker-compose-redis.yml"
            service: redis
networks:
    mongodb-network:
        driver: bridge
