services:
    frontend:
        restart: unless-stopped
        build: client
        volumes:
            - ./client/docker/nginx/production:/etc/nginx/conf.d
        ports:
            - "80:80"
