services:
    server:
        build: .
        volumes:
            - .:/usr/app/
            - /usr/app/node_modules
        ports:
            - "${PORT}:${PORT}"

    mongodb:
        image: mongo:4.4
        restart: always
        build: ./docker/db
        ports:
            - "27017:27017"
        volumes:
            - dbdata:/data/db
            - ./docker/db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        networks:
            - node-network
        command: ["--auth", "--keyFile", "/data/replica.key"]
        entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0"]
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
            - MONGO_INITDB_ROOT_DATABASE=chat

volumes:
    dbdata:

networks:
    node-network:
        driver: bridge
