version: "3.8"

services:
    mongodb-primary:
        container_name: mongodb-primary
        hostname: mongodb-primary
        image: mongo:latest
        restart: always
        build:
            context: ../
            dockerfile: db.Dockerfile
        volumes:
            - ./db/data/primary:/data/db
        ports:
            - "27017:27017"
        networks:
            - mongodb-network
        command: ["--bind_ip_all", "--replSet", "rs0", "--auth", "--keyFile", "/data/replica.key"]
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
            - MONGO_INITDB_ROOT_DATABASE=chat
    mongoinit:
        image: mongo:latest
        restart: "on-failure:5"
        depends_on:
            - mongodb-primary
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
            - MONGO_INITDB_ROOT_DATABASE=chat
        volumes:
            - ./db/rs-init.sh:/docker-entrypoint-initdb.d/rs-init.sh
        entrypoint: ["bash", "/docker-entrypoint-initdb.d/rs-init.sh"]
        networks:
            - mongodb-network
networks:
    mongodb-network:
        driver: bridge
