version: "3.8"

services:
    redis:
        image: redis:latest
        container_name: redis
        ports:
            - "6379:6379"
        volumes:
            - ./docker/redis/data:/data
        command: redis-server --save 20 1 --loglevel warning --requirepass 000000
    mongodb-primary:
        container_name: mongodb-primary
        hostname: mongodb-primary
        image: mongo:4.4
        restart: always
        build: ./docker/db
        volumes:
            - ./docker/db/data/primary:/data/db
        ports:
            - "27017:27017"
        depends_on:
            - mongodb-secondary-0
            - mongodb-secondary-1
        links:
            - mongodb-secondary-0
            - mongodb-secondary-1
        networks:
            - node-network
        command: ["--bind_ip_all", "--replSet", "rs0", "--auth", "--keyFile", "/data/replica.key"]
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
            - MONGO_INITDB_ROOT_DATABASE=chat
    mongodb-secondary-0:
        container_name: mongodb-secondary-0
        hostname: mongodb-secondary-0
        image: mongo:4.4
        restart: always
        build: ./docker/db
        volumes:
            - ./docker/db/data/secondary-0:/data/db
        ports:
            - "27018:27017"
        networks:
            - node-network
        command: ["--bind_ip_all", "--replSet", "rs0", "--auth", "--keyFile", "/data/replica.key"]
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
            - MONGO_INITDB_ROOT_DATABASE=chat
    mongodb-secondary-1:
        container_name: mongodb-secondary-1
        hostname: mongodb-secondary-1
        image: mongo:4.4
        restart: always
        build: ./docker/db
        volumes:
            - ./docker/db/data/secondary-1:/data/db
        ports:
            - "27019:27017"
        networks:
            - node-network
        command: ["--bind_ip_all", "--replSet", "rs0", "--auth", "--keyFile", "/data/replica.key"]
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
            - MONGO_INITDB_ROOT_DATABASE=chat
    mongoinit:
        image: mongo:4.4
        restart: "on-failure:5"
        depends_on:
            - mongodb-primary
            - mongodb-secondary-0
            - mongodb-secondary-1
        volumes:
            - ./docker/db/rs-init.sh:/docker-entrypoint-initdb.d/rs-init.sh
        entrypoint: ["bash", "/docker-entrypoint-initdb.d/rs-init.sh"]
        networks:
            - node-network
networks:
    node-network:
        driver: bridge
